# Generated by Django 3.1.1 on 2020-09-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meat_master_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo_url',
            field=models.TextField(blank=True),
        ),
    ]
